language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'create database snaildb'
  - echo "spring.profiles.active=travis" > src/main/resources/application.properties
  - cat src/main/resources/db/init/*.sql | mysql
